# Generated by Django 6.0 on 2025-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
