# Generated by Django 6.0 on 2026-01-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='BORROWED', help_text='Current status of the borrow record', max_length=10),
        ),
    ]
